name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@0.4.1
      with: 
        filename: 'webapp-${{ github.sha }}.zip'

    - uses: zdurham/s3-upload-github-action@master
      env:
        FILE: 'webapp-${{ github.sha }}.zip'
        AWS_REGION: 'us-east-1'
        S3_BUCKET: ${{ secrets.CODE_DEPLOY_S3_BUCKET_NAME }}
        S3_KEY: 'webapp-${{ github.sha }}.zip'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
       
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - uses: zdurham/s3-upload-github-action@master
      env:
        FILE: 'webapp-${{ github.sha }}.zip'
        AWS_REGION: 'us-east-1'
        S3_BUCKET: ${{ secrets.CODE_DEPLOY_S3_BUCKET_NAME }}
        S3_KEY: 'webapp-${{ github.sha }}.zip'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    - name: "CodeDeploy"
      run: aws deploy create-deployment --application-name ${{ secrets.CODE_DEPLOY_APPLICATION_NAME }} --deployment-group-name ${{ secrets.CODE_DEPLOY_GROUP_NAME }} --s3-location bucket=${{ secrets.CODE_DEPLOY_S3_BUCKET_NAME }},bundleType=zip,key=webapp-${{ github.sha }}.zip
 
 